Adding 1.1.16.wso2v2 version of pmml-evaluator and pmml-manager under AGPLv3 license
wso2-gpl/orbit pull request #4
Opened 2017-09-07 17:17 UTC by Niveathika92

2017-09-07 17:54 UTC, suhothayan requested changes

2017-09-07 17:54 UTC, suhothayan commented on pmml-evaluator/1.1.16.wso2v2/pom.xml
> +  ~ Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
Wrong license

2017-09-07 18:07 UTC, Niveathika92 commented on pmml-evaluator/1.1.16.wso2v2/pom.xml
> +  ~ Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
Fixed in 3b0c1d0

2017-09-11 08:42 UTC, suhothayan approved these changes

2017-09-11 08:44 UTC, merged